CREATE TABLE IF NOT EXISTS cards ( 
    id BIGSERIAL PRIMARY KEY,
    deck_id BIGINT NOT NULL,
    front VARCHAR(300) NOT NULL,
    back VARCHAR(2000) NOT NULL,
    retrievability DOUBLE PRECISION NOT NULL,
    stability DOUBLE PRECISION NOT NULL,
    difficulty DOUBLE PRECISION NOT NULL,
    due TIMESTAMPTZ(0) NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ(0) NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_deck FOREIGN KEY (deck_id) REFERENCES decks (id)
);
